config/routes.rb
Rails.application.routes.draw do
  get "pages/help"
  namespace :admin do
    get "dashboard/users"
    post "dashboard/update_user_role"
    get "dashboard/search_users"

    get "dashboard/items"
    get "dashboard/renting"
    post "dashboard/create_renting"
    patch "dashboard/toggle_renting"
    patch "dashboard/toggle_singleuse"
    delete "dashboard/delete_renting"
    patch "dashboard/update_quantity", to: "dashboard#update_quantity"
    get "dashboard/edit_renting", to: "dashboard#edit_renting"

    get "dashboard/purchased"
    post "dashboard/create_item"
    patch "dashboard/update_item"
    delete "dashboard/delete_item"
    get "dashboard/search_items"
    post "dashboard/create_purchase"
    post "dashboard/add_comment"
  end


  namespace :student do
    get "dashboard/items"
  end
  # Defines the root path route ("/")
  root "home#index"

  devise_for :users, controllers: {
    registrations: "users/registrations",
    sessions: "users/sessions",
    omniauth_callbacks: "users/omniauth_callbacks"
  }
  resources :purchases
  resources :rentings
  resources :roles
  # resources :items # Disabled as per request
  resources :categories
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "/help", to: "pages#help"  # New route for Help page
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
end

app/models/category.rb
class Category < ApplicationRecord
  include Loggable
  has_many :items

  validates :name, presence: true, uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_action :set_category, only: %i[ show edit update destroy ]

  # GET /categories or /categories.json
  def index
    @categories = Category.all
  end

  # GET /categories/1 or /categories/1.json
  def show
    log_view(@item)
  end

  # GET /categories/new
  def new
    @category = Category.new
  end

  # GET /categories/1/edit
  def edit
  end

  # POST /categories or /categories.json
  def create
    @category = Category.new(category_params)

    respond_to do |format|
      if @category.save
        format.html { redirect_to @category, notice: "Category was successfully created." }
        format.json { render :show, status: :created, location: @category }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /categories/1 or /categories/1.json
  def update
    respond_to do |format|
      if @category.update(category_params)
        format.html { redirect_to @category, notice: "Category was successfully updated." }
        format.json { render :show, status: :ok, location: @category }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @category.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /categories/1 or /categories/1.json
  def destroy
    @category.destroy!

    respond_to do |format|
      format.html { redirect_to categories_path, status: :see_other, notice: "Category was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_category
      @category = Category.find(params.expect(:id))
    end

    # Only allow a list of trusted parameters through.
    def category_params
      params.expect(category: [ :name ])
    end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/_category.html.erb
<div id="<%= dom_id category %>">
  <p class="my-5 text-content" data-font-size="16">
    <strong class="block font-medium mb-1">Name:</strong>
    <%= category.name %>
  </p>
</div>

app/views/categories/_form.html.erb
<%= form_with(model: category, class: "contents") do |form| %>
  <% if category.errors.any? %>
    <div id="error_explanation" class="bg-red-50 text-red-500 px-3 py-2 font-medium rounded-md mt-3">
      <h2 class="text-content" data-font-size="16"><%= pluralize(category.errors.count, "error") %> prohibited this category from being saved:</h2>

      <ul class="list-disc ml-6">
        <% category.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="my-5">
    <%= form.label :name, class: "text-content", data: { font_size: 16 } %>
    <%= form.text_field :name, class: ["block shadow-sm rounded-md border outline-hidden px-3 py-2 mt-2 w-full text-content", {"border-gray-400 focus:outline-blue-600": category.errors[:name].none?, "border-red-400 focus:outline-red-600": category.errors[:name].any?}], data: { font_size: 16 } %>
  </div>

  <div class="inline">
    <%= form.submit class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white inline-block font-medium cursor-pointer text-content", data: { font_size: 16 } %>
  </div>
<% end %>

app/views/categories/edit.html.erb
<% content_for :title, "Editing category" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-content" data-font-size="36">Editing category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Show this category", @category, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium text-content", data: { font_size: 16 } %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium text-content", data: { font_size: 16 } %>
</div>

app/views/categories/index.html.erb
<% content_for :title, "Categories" %>

<div class="w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block text-content" data-font-size="16" id="notice"><%= notice %></p>
  <% end %>

  <div class="flex justify-between items-center">
    <h1 class="font-bold text-4xl text-content" data-font-size="36">Categories</h1>
    <%= link_to "New category", new_category_path, class: "rounded-md px-3.5 py-2.5 bg-blue-600 hover:bg-blue-500 text-white block font-medium text-content", data: { font_size: 16 } %>
  </div>

  <div id="categories" class="min-w-full">
    <% if @categories.any? %>
      <% @categories.each do |category| %>
        <%= render category %>
        <p>
          <%= link_to "Show this category", category, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium text-content", data: { font_size: 16 } %>
        </p>
      <% end %>
    <% else %>
      <p class="text-center my-10 text-content" data-font-size="16">No categories found.</p>
    <% end %>
  </div>
</div>

app/views/categories/new.html.erb
<% content_for :title, "New category" %>

<div class="md:w-2/3 w-full">
  <h1 class="font-bold text-4xl text-content" data-font-size="36">New category</h1>

  <%= render "form", category: @category %>

  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium text-content", data: { font_size: 16 } %>
</div>

app/views/categories/show.html.erb
<% content_for :title, "Showing category" %>

<div class="md:w-2/3 w-full">
  <% if notice.present? %>
    <p class="py-2 px-3 bg-green-50 mb-5 text-green-500 font-medium rounded-md inline-block text-content" data-font-size="16" id="notice"><%= notice %></p>
  <% end %>

  <h1 class="font-bold text-4xl text-content" data-font-size="36">Showing category</h1>

  <%= render @category %>

  <%= link_to "Edit this category", edit_category_path(@category), class: "mt-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium text-content", data: { font_size: 16 } %>
  <%= link_to "Back to categories", categories_path, class: "ml-2 rounded-md px-3.5 py-2.5 bg-gray-100 hover:bg-gray-50 inline-block font-medium text-content", data: { font_size: 16 } %>
  <div class="inline-block ml-2">
    <%= button_to "Destroy this category", @category, method: :delete, class: "mt-2 rounded-md px-3.5 py-2.5 text-white bg-red-600 hover:bg-red-500 font-medium text-content", data: { font_size: 16 } %>
  </div>
</div>